### ISSUE TITLE
RETARDED WEEB

### ISSUE THREAD

**Issue by shxrkyy** [Uhhu738/frontend#28]
RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB

**Comment by Uhhu738** [comment]
> RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB

![image](https://user-images.githubusercontent.com/95198334/182481202-baed9a64-389a-4cd3-bc6f-090d7eb38141.png)

**Comment by Uhhu738** [comment]
> RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB RETARDED WEEB

I had thought you were chill at first lmao but I guess you're just a sensitive snowflake since you can't use your cheating Trojan 😆
